/** Declaration file generated by dts-gen nprogress声明文件*/

export const settings: {
  barSelector: string;
  easing: string;
  minimum: number;
  parent: string;
  positionUsing: string;
  showSpinner: boolean;
  speed: number;
  spinnerSelector: string;
  template: string;
  trickle: boolean;
  trickleRate: number;
  trickleSpeed: number;
};

export const status: any;

export const version: string;

export function configure(options?: any): any;

export function done(force?: any): any;

export function getPositioningCSS(): any;

export function inc(amount: any): any;

export function isRendered(): any;

export function isStarted(): any;

export function promise($promise: any): any;

export function remove(): void;

export function render(fromStart: any): any;

export function set(n: any): any;

export function start(): any;

export function trickle(): any;

export namespace configure {
  const prototype: {};
}

export namespace done {
  const prototype: {};
}

export namespace getPositioningCSS {
  const prototype: {};
}

export namespace inc {
  const prototype: {};
}

export namespace isRendered {
  const prototype: {};
}

export namespace isStarted {
  const prototype: {};
}

export namespace promise {
  const prototype: {};
}

export namespace remove {
  const prototype: {};
}

export namespace render {
  const prototype: {};
}

export namespace set {
  const prototype: {};
}

export namespace start {
  const prototype: {};
}

export namespace trickle {
  const prototype: {};
}
